// Code generated by tools/sqlc-gen-custom. DO NOT EDIT.
package storage

import (
	"context"

	"github.com/Go11Group/url_shortner/internal/repo/sqlc"
	"github.com/Go11Group/url_shortner/pkg/postgres"
	"github.com/google/uuid"
)

type StorageI interface {
	Close()
	WithinTransaction(ctx context.Context, fn func(StorageI) error) error
	Url() UrlRepositoryI
}

type UrlRepositoryI interface {
	CreateUrl(ctx context.Context, arg *sqlc.CreateUrlParams) (sqlc.Url, error)
	GetUrlByCode(ctx context.Context, shortCode string) (sqlc.Url, error)
	IncrementClicks(ctx context.Context, id uuid.UUID) error
}

type storageImpl struct {
	*sqlc.Queries
	pg *postgres.Postgres
}

func NewStorage(pg *postgres.Postgres) StorageI {
	return &storageImpl{
		Queries: sqlc.New(pg.Pool),
		pg:      pg,
	}
}

func (s *storageImpl) Close() { s.pg.Close() }

func (s *storageImpl) WithinTransaction(ctx context.Context, fn func(StorageI) error) error {
	tx, err := s.pg.Pool.Begin(ctx)
	if err != nil {
		return err
	}

	defer tx.Rollback(ctx)

	qtx := s.Queries.WithTx(tx)
	err = fn(&storageImpl{Queries: qtx, pg: s.pg})
	if err != nil {
		return err
	}

	return tx.Commit(ctx)
}

func (s *storageImpl) Url() UrlRepositoryI { return s }
