// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID          uuid.UUID          `json:"id"`
	OriginalUrl string             `json:"original_url"`
	ShortCode   string             `json:"short_code"`
	Clicks      *int32             `json:"clicks"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
