// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// @interface UrlRepositoryI
	CreateUrl(ctx context.Context, arg *CreateUrlParams) (Url, error)
	// @interface UrlRepositoryI
	GetUrlByCode(ctx context.Context, shortCode string) (Url, error)
	// @interface UrlRepositoryI
	IncrementClicks(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
