// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO urls (original_url, short_code)
VALUES ($1, $2)
RETURNING id, original_url, short_code, clicks, created_at
`

type CreateUrlParams struct {
	OriginalUrl string `json:"original_url"`
	ShortCode   string `json:"short_code"`
}

// @interface UrlRepositoryI
func (q *Queries) CreateUrl(ctx context.Context, arg *CreateUrlParams) (Url, error) {
	row := q.db.QueryRow(ctx, createUrl, arg.OriginalUrl, arg.ShortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.Clicks,
		&i.CreatedAt,
	)
	return i, err
}

const getUrlByCode = `-- name: GetUrlByCode :one
SELECT id, original_url, short_code, clicks, created_at FROM urls
WHERE short_code = $1 LIMIT 1
`

// @interface UrlRepositoryI
func (q *Queries) GetUrlByCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getUrlByCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.Clicks,
		&i.CreatedAt,
	)
	return i, err
}

const incrementClicks = `-- name: IncrementClicks :exec
UPDATE urls SET clicks = clicks + 1 WHERE id = $1
`

// @interface UrlRepositoryI
func (q *Queries) IncrementClicks(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementClicks, id)
	return err
}
